version: '3.8'

services:
  # Backend FastAPI service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - uploaded_videos:/app/uploads
    networks:
      - sales_coach_network
    depends_on:
      - postgres
      - redis

  # Frontend React service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - sales_coach_network
    environment:
      - REACT_APP_API_URL=http://localhost:8000

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: sales_coach_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - sales_coach_network

  # Redis for caching and Celery
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - sales_coach_network

  # Celery worker for async processing
  celery_worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: celery -A app.celery_app worker --loglevel=info
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - uploaded_videos:/app/uploads
    networks:
      - sales_coach_network
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data:
  redis_data:
  uploaded_videos:

networks:
  sales_coach_network:
    driver: bridge 